### ISSUE TITLE
Crashes while running

### ISSUE THREAD

**Issue by softwareklinic** [andresilvasantos/bitprophet#2] opened 2018-04-20 04:37 UTC
Bot keeps crashing every few hours

/Users/FamilyMac/Downloads/bitprophet-master/strategies/buydip.js:218
        if(order.price.toFixed(8) != pair.sellTarget.toFixed(8) || amountToSell > sellOrderAmount) {
                                                     ^

TypeError: pair.sellTarget.toFixed is not a function
    at Object.manageSellOrder (/Users/FamilyMac/Downloads/bitprophet-master/strategies/buydip.js:218:54)
    at Object.process (/Users/FamilyMac/Downloads/bitprophet-master/strategies/buydip.js:75:18)
    at create.process (/Users/FamilyMac/Downloads/bitprophet-master/strategy_generator.js:187:25)
    at Object.process (/Users/FamilyMac/Downloads/bitprophet-master/strategy_manager.js:45:44)
    at Timeout.processStrategies [as _onTimeout] (/Users/FamilyMac/Downloads/bitprophet-master/bitprophet.js:186:29)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)

**Comment by andresilvasantos** [comment] 2018-04-20 04:42
Did you change anything in __buydip.js__?

Do you have paper trading active? Can you please show me your __index.js__?

**Comment by softwareklinic** [comment] 2018-04-20 04:54
module.exports = {
    strategies: {
        alertsrsi: {
            name: "Alerts RSI",
            targetMarket: "BTC"
        },
        alertsichimoku: {
            name: "Alerts Ichimoku",
            targetMarket: "BTC"
        },
        buydip: {
            name: "Buy Dip",
            paperTrading: false,
            buyAmountMarket: 0.03,
            profitTarget: 5.0,
            maxLoss: 2.0,
            maxTradingPairs: 5,
            targetMarket: "BTC"

        }
    }
}

**Comment by andresilvasantos** [comment] 2018-04-20 05:11
This is strange. It is telling that `sellTarget` is not a valid number when it should be.
I need to run some tests.

If you want, for now, you can replace that condition with the following

```
if(amountToSell > sellOrderAmount) {
       if(pair.trySellTimestamp && Date.now() - pair.trySellTimestamp < 5 * 1000) return
       pair.trySellTimestamp = Date.now()
       recreateSellOrder()
}
```
I'll get back to you when I know what's happening.

**Comment by softwareklinic** [comment] 2018-04-20 05:12
Ty will try it out

**Comment by softwareklinic** [comment] 2018-04-20 14:56
Made the change -- running it - will let you know the feedback

**Comment by softwareklinic** [comment] 2018-04-20 17:40
didnt crash so far after the code change

**Comment by andresilvasantos** [comment] 2018-04-20 17:42
Nice, but I still need to fix the problem. I'll leave this issue open till I update the code.

**Comment by bluestack111** [comment] 2018-04-21 20:55
+1 ... having the same issue

**Comment by andresilvasantos** [comment] 2018-04-22 21:53
I think the problem is solved with [0.4.5](https://github.com/andresilvasantos/bitprophet/commit/99ef339abcef8a9c1c79d17d10376cf6894e5a19). 

@softwareklinic and @bluestack111 let me know if it works well now.

**Comment by softwareklinic** [comment] 2018-04-22 22:09
Sure will tonight


Regards
Keyur

**Comment by bluestack111** [comment] 2018-04-23 19:48
@andresilvasantos - It seems that everything is working as expected after the fix. Thank you

**Comment by softwareklinic** [comment] 2018-04-23 21:11
So, I download master again --- it will have all the fixes?? right?

**Comment by andresilvasantos** [comment] 2018-04-23 21:14
@bluestack111 Thank you for the feedback!

@softwareklinic This issue seems solved. Which fix besides this one are you looking for?

**Comment by softwareklinic** [comment] 2018-04-23 21:18
I think thats the only one...

**Comment by andresilvasantos** [comment] 2018-04-23 21:21
Nice, go and try it! I'll close this issue, reopen it if you get the same error.

**Closed as completed by andresilvasantos** 2018-04-23 21:21 UTC
Labels: bug

**Comment by softwareklinic** [comment] 2018-04-23 21:35
What does this number indicate [PT] Buy Dip - 102 0 0.00%

102? or 109? or 114?

**Comment by andresilvasantos** [comment] 2018-04-23 21:46
[paper_trading] strategy_name - **valid_pairs** trading_pairs profit

I need to improve the docs on this.

In Telegram, you can type list buydip, and it will show you every valid and trading pairs for that strategy.

**Comment by softwareklinic** [comment] 2018-04-23 21:59
thank you
