### ISSUE TITLE
Sell/Cancelled Loop

### ISSUE THREAD

**Issue by itsjNathan** [andresilvasantos/bitprophet#21] opened 2018-05-04 03:42 UTC
im on the latest version on BitProphet v0.6.7

![image](https://user-images.githubusercontent.com/31687526/39612218-10f2c432-4f90-11e8-9cc7-f0e2e779322e.png)

**Comment by andresilvasantos** [comment] 2018-05-04 03:45
Duplicate of #13

**Closed as completed by andresilvasantos** 2018-05-04 03:45 UTC
Labels: duplicate
